name: Build and Release NetShift

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'
      - 'readme.md'
      - '**/README.md'
      - '**/readme.md'
      - '.github/workflows/deploy.yml'

jobs:
  build-sign-release:
    runs-on: windows-latest

    env:
      BASE_DIR: D:\a\NetShift\NetShift
      NetShiftExe: NetShift\bin\Release\net8.0-windows\NetShift.exe
      NetShiftServiceExe: NetShiftService\bin\x64\Release\NetShiftService.exe
      NetShiftSetupMsi: NetShiftSetup\bin\x64\Release\NetShiftSetup.msi
      NetShiftInstallerExe: NetShiftSetup\bin\x64\Release\NetShiftInstaller.exe

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild (for initial project builds)
      uses: microsoft/setup-msbuild@v2

    - name: Install WiX Toolset manually (WiX 5)
      run: choco install wixtoolset --version=5.0.0

    - name: Build NetShift App
      run: msbuild NetShift\NetShift.csproj /p:Configuration=Release

    - name: Sign NetShift.exe
      uses: ./github/actions/actions-code-signer
      with:
        input: NetShift\bin\Release\net8.0-windows\NetShift.exe
        output: NetShift\bin\Release\net8.0-windows\Signed\
    
    - name: Build NetShiftService App
      run: msbuild NetShiftService\NetShiftService.csproj /p:Configuration=Release

    - name: Sign NetShiftService.exe
      uses: ./github/actions/actions-code-signer
      with:
        input: NetShiftService\bin\x64\Release\NetShiftService.exe
        output: NetShiftService\bin\x64\Release\Signed\

    - name: Copy Signed NetShiftService into Setup
      run: |
        Copy-Item "NetShiftService\bin\x64\Release\Signed\NetShiftService.exe" -Destination "NetShiftSetup\NetShiftService.exe" -Force

    - name: Harvest NetShift files (heat.exe)
      run: |
        & "C:\Program Files\WiX Toolset v5.0\bin\x64\heat.exe" dir "NetShift\bin\Release\net8.0-windows" `
          -dr APPFOLDER -cg NetShiftFiles -gg -scom -sreg -srd -template:fragment `
          -out "NetShiftSetup\NetShiftFiles.wxs"

    - name: Build NetShiftSetup.msi (Package.wxs)
      run: |
        & tools\wix\wix.exe build NetShiftSetup\Package.wxs -o NetShiftSetup\bin\x64\Release\NetShiftSetup.msi

    - name: Sign NetShiftSetup.msi
      uses: ./github/actions/actions-code-signer
      with:
        input: NetShiftSetup\bin\x64\Release\NetShiftSetup.msi
        output: NetShiftSetup\bin\x64\Release\Signed\

    - name: Build NetShiftInstaller.exe (Bundle.wxs)
      run: |
        & tools\wix\wix.exe build NetShiftSetup\Bundle.wxs -o NetShiftSetup\bin\x64\Release\NetShiftInstaller.exe

    - name: Sign NetShiftInstaller.exe
      uses: ./github/actions/actions-code-signer
      with:
        input: NetShiftSetup\bin\x64\Release\NetShiftInstaller.exe
        output: NetShiftSetup\bin\x64\Release\Signed\

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NetShift-Build
        path: |
          NetShiftSetup\bin\x64\Release\Signed\NetShiftSetup.msi
          NetShiftSetup\bin\x64\Release\Signed\NetShiftInstaller.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          NetShiftSetup\bin\x64\Release\Signed\NetShiftSetup.msi
          NetShiftSetup\bin\x64\Release\Signed\NetShiftInstaller.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
