name: Build, Sign, and Release NetShift

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  actions: read
  contents: write
  packages: write
  id-token: write

env:
  SIGN_CODE: false # 🔥 Toggle code signing
  BASE_DIR: ${{ github.workspace }}
  ARTIFACTS_DIR: ${{ github.workspace }}\artifacts
  SolutionPath: ${{ github.workspace }}\NetShift.sln
  SetupPath: ${{ github.workspace }}\NetShiftSetup
  NetShiftBin: ${{ github.workspace }}\NetShift\bin\x64\Release\net8.0-windows\net8.0-windows
  NetShiftExe: ${{ github.workspace }}\NetShift\bin\x64\Release\net8.0-windows\net8.0-windows\NetShift.exe
  NetShiftServiceBin: ${{ github.workspace }}\NetShiftService\bin\x64\Release
  NetShiftServiceExe: ${{ github.workspace }}\NetShiftService\bin\x64\Release\NetShiftService.exe
  NetShiftInstallerExe: ${{ github.workspace }}\artifacts\NetShiftInstaller.exe
  RCEDIT_PATH: ${{ github.workspace }}\tools\rcedit\rcedit-x64.exe

jobs:
  build-sign-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Create artifacts directory
        run: New-Item -ItemType Directory -Force -Path "${{ env.ARTIFACTS_DIR }}"
        shell: powershell

      - name: Restore NuGet packages
        run: nuget restore "${{ env.SolutionPath }}"
        shell: powershell

      - name: Build NetShift project
        run: msbuild NetShift\NetShift.csproj /p:Configuration=Release /p:Platform=x64
        env:
          UseSharedCompilation: false

      - name: Stamp version into NetShift.exe
        run: |
          & "${{ env.RCEDIT_PATH }}" "${{ env.NetShiftExe }}" --set-version-string "ProductVersion" "${{ github.ref_name }}"
          & "${{ env.RCEDIT_PATH }}" "${{ env.NetShiftExe }}" --set-version-string "FileVersion" "${{ github.ref_name }}"
        shell: powershell

      - name: Rebuild NetShift project after stamping
        run: msbuild NetShift\NetShift.csproj /p:Configuration=Release /p:Platform=x64
        env:
          UseSharedCompilation: false

      - name: Conditionally sign NetShift.exe
        if: env.SIGN_CODE == 'true'
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.CODESIGN_USERNAME }}
          password: ${{ secrets.CODESIGN_PASSWORD }}
          credential_id: ${{ secrets.CODESIGN_CREDENTIAL_ID }}
          totp_secret: ${{ secrets.CODESIGN_TOTP_SECRET }}
          file_path: ${{ env.NetShiftExe }}
          output_dir_path: ${{ env.ARTIFACTS_DIR }}
          environment_name: PROD
          signing_method: v2
          malware_block: false

      - name: Replace NetShift.exe with signed version
        if: env.SIGN_CODE == 'true'
        run: Copy-Item "${{ env.ARTIFACTS_DIR }}\NetShift.exe" "${{ env.NetShiftExe }}" -Force
        shell: powershell

      - name: Build NetShiftService project
        run: msbuild NetShiftService\NetShiftService.csproj /p:Configuration=Release /p:Platform=x64
        env:
          UseSharedCompilation: false

      - name: Stamp version into NetShiftService.exe
        run: |
          & "${{ env.RCEDIT_PATH }}" "${{ env.NetShiftServiceExe }}" --set-version-string "ProductVersion" "${{ github.ref_name }}"
          & "${{ env.RCEDIT_PATH }}" "${{ env.NetShiftServiceExe }}" --set-version-string "FileVersion" "${{ github.ref_name }}"
        shell: powershell

      - name: Rebuild NetShiftService project after stamping
        run: msbuild NetShiftService\NetShiftService.csproj /p:Configuration=Release /p:Platform=x64
        env:
          UseSharedCompilation: false

      - name: Conditionally sign NetShiftService.exe
        if: env.SIGN_CODE == 'true'
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.CODESIGN_USERNAME }}
          password: ${{ secrets.CODESIGN_PASSWORD }}
          credential_id: ${{ secrets.CODESIGN_CREDENTIAL_ID }}
          totp_secret: ${{ secrets.CODESIGN_TOTP_SECRET }}
          file_path: ${{ env.NetShiftServiceExe }}
          output_dir_path: ${{ env.ARTIFACTS_DIR }}
          environment_name: PROD
          signing_method: v2
          malware_block: false

      - name: Replace NetShiftService.exe with signed version
        if: env.SIGN_CODE == 'true'
        run: Copy-Item "${{ env.ARTIFACTS_DIR }}\NetShiftService.exe" "${{ env.NetShiftServiceExe }}" -Force
        shell: powershell

      - name: Debug build output directory
        run: dir "${{ env.NetShiftBin }}" -Recurse
        shell: powershell

      - name: Build Inno Setup Installer
        uses: jovibor/action-innosetup@v1
        with:
          script: ${{ env.SetupPath }}\setup.iss
          output: ${{ env.NetShiftInstallerExe }}

      - name: Conditionally sign NetShiftInstaller.exe
        if: env.SIGN_CODE == 'true'
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.CODESIGN_USERNAME }}
          password: ${{ secrets.CODESIGN_PASSWORD }}
          credential_id: ${{ secrets.CODESIGN_CREDENTIAL_ID }}
          totp_secret: ${{ secrets.CODESIGN_TOTP_SECRET }}
          file_path: ${{ env.NetShiftInstallerExe }}
          output_dir_path: ${{ env.ARTIFACTS_DIR }}
          environment_name: PROD
          signing_method: v2
          malware_block: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NetShift-Installer
          path: ${{ env.NetShiftInstallerExe }}
          retention-days: 7

  release:
    needs: build-sign-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: NetShift-Installer
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/NetShiftInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}