name: Build and Release NetShift

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'
      - 'readme.md'
      - '**/README.md'
      - '**/readme.md'

permissions:
  actions: read
  contents: read
  packages: write
  id-token: write

jobs:
  build-sign-release:
    runs-on: windows-latest

    env:
      BASE_DIR: ${{ github.workspace }}
      ARTIFACTS_DIR: ${{ github.workspace }}\artifacts
      SolutionPath: ${{ github.workspace }}\NetShift.sln
      SetupPath: ${{ github.workspace }}\NetShiftSetup
      NetShiftBin: ${{ github.workspace }}\NetShift\bin\x64\Release\net8.0-windows\net8.0-windows
      NetShiftExe: ${{ github.workspace }}\NetShift\bin\x64\Release\net8.0-windows\net8.0-windows\NetShift.exe
      NetShiftServiceBin: ${{ github.workspace }}\NetShiftService\bin\x64\Release\net8.0-windows
      NetShiftServiceExe: ${{ github.workspace }}\NetShiftService\bin\x64\Release\net8.0-windows\NetShiftService.exe
      NetShiftSetupMsi: ${{ github.workspace }}\NetShiftSetup\bin\Release\NetShiftSetup.msi
      NetShiftInstallerExe: ${{ github.workspace }}\NetShiftSetup\bin\Release\NetShiftInstaller.exe
      WIX_PATH: ${{ github.workspace }}\tools\wix

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Unblock WiX Executables
        run: |
          Get-ChildItem "${{ env.WIX_PATH }}" -Filter *.exe | Unblock-File
        shell: powershell

      - name: Restore NuGet Packages
        run: nuget restore "${{ env.SolutionPath }}"

      - name: Create artifacts directory
        run: New-Item -ItemType Directory -Force -Path "${{ env.ARTIFACTS_DIR }}"
        shell: powershell

      - name: Build NetShift Project
        run: msbuild NetShift\NetShift.csproj /p:Configuration=Release /p:Platform=x64

      - name: Sign NetShift.exe
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.CODESIGN_USERNAME }}
          password: ${{ secrets.CODESIGN_PASSWORD }}
          credential_id: ${{ secrets.CODESIGN_CREDENTIAL_ID }}
          totp_secret: ${{ secrets.CODESIGN_TOTP_SECRET }}
          file_path: ${{ env.NetShiftExe }}
          output_path: ${{ env.ARTIFACTS_DIR }}
          environment_name: PROD
          signing_method: v2
          malware_block: false

      - name: Copy signed NetShift.exe back
        run: |
          Copy-Item "${{ env.ARTIFACTS_DIR }}\NetShift.exe" -Destination "${{ env.NetShiftExe }}" -Force
        shell: powershell

      - name: Build NetShiftService Project
        run: msbuild NetShiftService\NetShiftService.csproj /p:Configuration=Release /p:Platform=x64

      - name: Sign NetShiftService.exe
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.CODESIGN_USERNAME }}
          password: ${{ secrets.CODESIGN_PASSWORD }}
          credential_id: ${{ secrets.CODESIGN_CREDENTIAL_ID }}
          totp_secret: ${{ secrets.CODESIGN_TOTP_SECRET }}
          file_path: ${{ env.NetShiftServiceExe }}
          output_path: ${{ env.ARTIFACTS_DIR }}
          environment_name: PROD
          signing_method: v2
          malware_block: false

      - name: Copy signed NetShiftService.exe back
        run: |
          Copy-Item "${{ env.ARTIFACTS_DIR }}\NetShiftService.exe" -Destination "${{ env.NetShiftServiceExe }}" -Force
        shell: powershell

      - name: Copy signed NetShiftService.exe into Setup
        run: |
          Copy-Item "${{ env.NetShiftServiceExe }}" "${{ env.SetupPath }}\NetShiftService.exe" -Force
        shell: powershell

      - name: Harvest NetShift Files (heat.exe)
        run: |
          & "${{ env.WIX_PATH }}\heat.exe" dir "${{ env.NetShiftBin }}" `
            -dr APPFOLDER -cg NetShiftFiles -gg -scom -sreg -srd -template:fragment `
            -out "${{ env.SetupPath }}\NetShiftFiles.wxs"
        shell: powershell

      - name: Build NetShiftSetup.msi
        run: |
          & "${{ env.WIX_PATH }}\wix.exe" build NetShiftSetup\Package.wxs -o NetShiftSetup\bin\Release\NetShiftSetup.msi
        shell: powershell

      - name: Sign NetShiftSetup.msi
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.CODESIGN_USERNAME }}
          password: ${{ secrets.CODESIGN_PASSWORD }}
          credential_id: ${{ secrets.CODESIGN_CREDENTIAL_ID }}
          totp_secret: ${{ secrets.CODESIGN_TOTP_SECRET }}
          file_path: ${{ env.NetShiftSetupMsi }}
          output_path: ${{ env.ARTIFACTS_DIR }}
          environment_name: PROD
          signing_method: v2
          malware_block: false

      - name: Copy signed NetShiftSetup.msi back
        run: |
          Copy-Item "${{ env.ARTIFACTS_DIR }}\NetShiftSetup.msi" -Destination "${{ env.NetShiftSetupMsi }}" -Force
        shell: powershell

      - name: Build NetShiftInstaller.exe
        run: |
          & "${{ env.WIX_PATH }}\wix.exe" build NetShiftSetup\Bundle.wxs -o NetShiftSetup\bin\Release\NetShiftInstaller.exe
        shell: powershell

      - name: Sign NetShiftInstaller.exe
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.CODESIGN_USERNAME }}
          password: ${{ secrets.CODESIGN_PASSWORD }}
          credential_id: ${{ secrets.CODESIGN_CREDENTIAL_ID }}
          totp_secret: ${{ secrets.CODESIGN_TOTP_SECRET }}
          file_path: ${{ env.NetShiftInstallerExe }}
          output_path: ${{ env.ARTIFACTS_DIR }}
          environment_name: PROD
          signing_method: v2
          malware_block: false

      - name: Copy signed NetShiftInstaller.exe back
        run: |
          Copy-Item "${{ env.ARTIFACTS_DIR }}\NetShiftInstaller.exe" -Destination "${{ env.NetShiftInstallerExe }}" -Force
        shell: powershell

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NetShift-Build
          path: |
            NetShiftSetup\bin\Release\NetShiftSetup.msi
            NetShiftSetup\bin\Release\NetShiftInstaller.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            NetShiftSetup\bin\Release\NetShiftSetup.msi
            NetShiftSetup\bin\Release\NetShiftInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}